{{ if .Values.dev.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: debug
  labels:
    {{- include "k8s-ephemeral-storage-metrics.labels" . | nindent 4 }}
    app.kubernetes.io/name: k8s-ephemeral-storage-metrics-debug
spec:
  type: ClusterIP
  selector:
    {{- include "k8s-ephemeral-storage-metrics.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 30002
      targetPort: debug
      name: debug
---

apiVersion: v1
kind: Service
metadata:
  name: pprof
  labels:
    {{- include "k8s-ephemeral-storage-metrics.labels" . | nindent 4 }}
    app.kubernetes.io/name: k8s-ephemeral-storage-metrics-debug
spec:
  type: ClusterIP
  selector:
    {{- include "k8s-ephemeral-storage-metrics.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 6060
      targetPort: pprof
      name: pprof
 {{ end }}
