{{ if .Values.prometheus.enable }}
{{ if .Values.serviceMonitor.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "k8s-ephemeral-storage-metrics.fullname" . }}
  namespace: {{ template "k8s-ephemeral-storage-metrics.namespace" . }}
  labels:
  {{- include "k8s-ephemeral-storage-metrics.labels" . | nindent 4 }}
{{- with .Values.serviceMonitor.additionalLabels }}
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
      scheme: {{ .Values.serviceMonitor.scheme | default "http" }}
      interval: "{{ .Values.interval }}s"
{{- if .Values.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml .Values.serviceMonitor.tlsConfig | nindent 8 }}
{{- end }}
{{- if .Values.serviceMonitor.bearerTokenFile }}
      bearerTokenFile: {{ .Values.serviceMonitor.bearerTokenFile }}
{{- end }}
{{- if .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
{{ toYaml .Values.serviceMonitor.metricRelabelings | indent 8 }}
{{- end }}
{{- if .Values.serviceMonitor.relabelings }}
      relabelings:
{{ toYaml .Values.serviceMonitor.relabelings | indent 8 }}
{{- end }}
  namespaceSelector:
    matchNames:
      - {{ template "k8s-ephemeral-storage-metrics.namespace" . }}
  selector:
    matchLabels:
      {{- include "k8s-ephemeral-storage-metrics.selectorLabels" . | nindent 6 }}
  {{- if .Values.serviceMonitor.targetLabels }}
  targetLabels:
    {{- range .Values.serviceMonitor.targetLabels }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- if .Values.serviceMonitor.podTargetLabels }}
  podTargetLabels:
    {{- range .Values.serviceMonitor.podTargetLabels }}
    - {{ . }}
    {{- end }}
  {{- end }}
{{ end }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "k8s-ephemeral-storage-metrics.fullname" . }}
  namespace: {{ template "k8s-ephemeral-storage-metrics.namespace" . }}
  labels:
    {{- include "k8s-ephemeral-storage-metrics.labels" . | nindent 6 }}
spec:
  type: ClusterIP
  selector:
  {{- include "k8s-ephemeral-storage-metrics.selectorLabels" . | nindent 6 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port  }}
      protocol: TCP
      targetPort: {{ .Values.metrics.port  }}
{{ end }}
