{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: {{ .Release.Name }}
  {{- include "k8s-ephemeral-storage-metrics.labels" . | nindent 4 }}
  name: {{ include "k8s-ephemeral-storage-metrics.serviceAccountName" . }}
  namespace: {{ template "k8s-ephemeral-storage-metrics.namespace" . }}
{{- end }}

{{- if .Values.rbac.create }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "k8s-ephemeral-storage-metrics.fullname" . }}
  labels:
  {{- include "k8s-ephemeral-storage-metrics.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes","nodes/proxy", "nodes/stats", "pods"]
    verbs: ["get","list", "watch"]
{{-  if .Values.kubeRBACProxy.enabled  }}
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
{{- end }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "k8s-ephemeral-storage-metrics.fullname" . }}
  labels:
  {{- include "k8s-ephemeral-storage-metrics.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-ephemeral-storage-metrics.serviceAccountName" . }}
    namespace: {{ template "k8s-ephemeral-storage-metrics.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "k8s-ephemeral-storage-metrics.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
